# Generated by Django 5.1.4 on 2024-12-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('postUser', 'postUser'), ('klientUser', 'klientUser')], default='klientUser', max_length=18),
        ),
    ]
