# Generated by Django 5.1.4 on 2024-12-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_userprofile_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('ownerUser', 'ownerUser'), ('klientUser', 'klientUser')], default='klientUser', max_length=18),
        ),
    ]
