# Generated by Django 5.1.4 on 2024-12-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_rename_user_post_owner_alter_userprofile_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='user',
            new_name='owner',
        ),
    ]
