# Generated by Django 5.1.4 on 2024-12-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_chat_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitem',
            old_name='post',
            new_name='post_item',
        ),
        migrations.RenameField(
            model_name='saveitem',
            old_name='save',
            new_name='save_item',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской'), ('Не указывать', 'Не указывать')], default='Другой', max_length=99),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, max_length=222, null=True),
        ),
    ]
